### ISSUE TITLE
Replace all reference to  https://github.com/arcturusannamalai/open-tamil/tree/master/ with correct url in README

### ISSUE THREAD

**Issue by kracekumar** [Ezhil-Language-Foundation/open-tamil#111]

**Comment by arcturusannamalai** [comment]
வணக்கம் செங்கொட்டுவேல், 
திருத்தங்களுக்கு நன்றி. எங்கள் "issue"-வில் உள்ளவற்றையோ, அல்லது உங்களுக்கு பிடித்தவற்றையொ தொடர்ந்து பங்களியுங்கள்.

நன்றி.
முத்து
