### ISSUE TITLE
Error in "splitMeiUyir"

### ISSUE THREAD

**Issue by vrindaprabhu** [Ezhil-Language-Foundation/open-tamil#117]
`utf8.splitMeiUyir(u"தொ")`

> ValueError                                Traceback (most recent call last)
> <ipython-input-430-a684847b08da> in <module>()
> ----> 1 utf8.splitMeiUyir(u"தொ")
> 
> C:\Users\vrindaprabhu\AppData\Local\Continuum\Anaconda\lib\site-packages\tamil\utf8.pyc in splitMeiUyir(uyirmei_char)
>     506 
>     507     if uyirmei_char not in grantha_uyirmei_letters:
> --> 508         raise ValueError("Passed input letter '%s' is not tamil letter" % uyirmei_char)
>     509 
>     510     idx = grantha_uyirmei_letters.index(uyirmei_char)
> 
> <type 'str'>: (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u"Passed input letter '\u0ba4\u0bc6\u0bbe' is not tamil letter", 21, 24, 'ordinal not in range(128)'))

**Comment by arcturusannamalai** [comment]
I think the input needs to be unicode normalized. In this case "தெ" + கால்  வாங்கி குறி ஒரு வினோதமாக வரும் என்று எண்ணுகிறேன்.

இதனை சரி செய்யவேண்டும். நன்றி.
