### ISSUE TITLE
முப்பத்'தி' -> முப்பத்'து'

### ISSUE THREAD

**Issue by thaache** [Ezhil-Language-Foundation/open-tamil#136]
அருமையான முயற்சி. சில திருத்தங்கள் -> http://tamilpesu.us/number/ இல் `Result: '{"result": "முப்பத்தி நான்கு"}'` என்பதைப்பார்க்கிறேன்.
இருபத்து இரண்டு அ| இருபத்திரண்டு
முப்பத்து மூன்று
நாற்பத்து நான்கு
ஐம்பத்து ஐந்து அ| ஐம்பத்தைந்து
அறுபத்து ஆறு அ| அறுபத்தாறு
எழுபத்து ஏழு அ| எழுபத்தேழு
எண்பத்து எட்டு அ| எண்பத்தெட்டு
தொண்ணூற்று ஒன்பது அ| தொணூற்றொன்பது
எழுனூற்று ஐம்பத்து ஒன்பது அ| எழுனூற்றைம்பத்தொன்பது
ஒன்பதாயிரத்து தொள்ளாயிரத்து தொண்ணூற்றொன்பது

**Comment by msathia** [comment]
I have code to close this. Can someone give me access to repo to do PR? I am not able to send PR.

**Comment by ssurenr** [comment]
@msathia Could you elaborate why you couldn't send PR?

**Comment by msathia** [comment]
I cloned https://github.com/Ezhil-Language-Foundation/open-tamil.git. Created a new branch locally from master and tried to push the branch to remote.
 @ ~/open-tamil * bugfix/#136
  master
 [465] → git push --set-upstream origin bugfix/#136
remote: Permission to Ezhil-Language-Foundation/open-tamil.git denied to msathia.
fatal: unable to access 'https://github.com/Ezhil-Language-Foundation/open-tamil.git/': The requested URL returned error: 403

**Comment by ssurenr** [comment]
I thought the same when I did my commit. What you are doing is not a pull request. You are trying to push your changes directly to upstream. Fork `Ezhil-Language-Foundation/open-tamil` repository(upstream), you will get a repo named `msathia/open-tamil`(origin). Push you changes there. When you visit your forked repository, you will find an option to create a PR.
Ref: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by msathia** [comment]
Ok. We are doing fork and PR. Thanks. I was using always a branch to master/develop PR. Let me update the contributing guidelines later for this. Thank you!!

**Comment by msathia** [comment]
Sent a PR for this. Thanks.

**Comment by arcturusannamalai** [comment]
@msathia sorry I was traveling and not able to help you here; thanks for assistance @ssurenr

**Comment by arcturusannamalai** [comment]
@msathia - there are some regressions; please take a look once again.
e.g. number 1729 is forced to be generated as
        expected = u"ஓர் ஆயிரத்து எழுநூற்று இருபத் தொன்பது"

unlike the previously correct data.

**Comment by msathia** [comment]
" இருபத் தொன்பது" with space? which file are you seeing this? it should be other way round "இருபத்தொன்பது"

**Comment by msathia** [comment]
https://travis-ci.org/Ezhil-Language-Foundation/open-tamil/builds/357574596. Found those. Fixed it. Pls check the Travis CI passing all tests. Thanks.

**Comment by msathia** [comment]
Can we close this issue as the fixes are committed?

**Comment by arcturusannamalai** [comment]
நன்றி, சத்தியா!
