### ISSUE TITLE
Package tools from open-tamil for windows 32/64 on Python 2.7+

### ISSUE THREAD

**Issue by arcturusannamalai** [Ezhil-Language-Foundation/open-tamil#149]
Currently we have 6 command line tools from open-tamil package (see issue #148) - but these are not usually available for non-developer.  However not to lose heart, we can package them.

We may use the setup.py to build the package for Windows 32/64 bit as a self-extracting msi package files. See: https://docs.python.org/2/distutils/builtdist.html

I need a volunteer for Win32 builds; I have a Win 64 machine to build the alternative. 

Other platforms can also be supported Mac OS X and Linux, but not important at this time. Please add your thoughts below.

**Comment by ssurenr** [comment]
It would be better if we remove `.py` extension while copying executables to `bin`.

**Comment by arcturusannamalai** [comment]
@ssurenr  in Python world there is django-admin.py etc which are binaries. It is well understood to have py extension. Alternative is to have a fully compiled executable, which is not what I am proposing.

**Comment by ssurenr** [comment]
Understood!

**Comment by arcturusannamalai** [comment]
No.

**Comment by arcturusannamalai** [comment]
We will sunset Python 2.7 as per https://github.com/Ezhil-Language-Foundation/open-tamil/issues/181
