### ISSUE TITLE
வார்தை எண்ணி - opentamilweb does not work ok

### ISSUE THREAD

**Issue by arcturusannamalai** [Ezhil-Language-Foundation/open-tamil#150]
வார்தை எண்ணி
http://tamilpesu.us does not work ok.

**Comment by abuvanth** [comment]
Fixed [https://github.com/Ezhil-Language-Foundation/open-tamil/pull/151/commits/816a2f77a1b18973dadeb22de94b16bc6ca5cdbd](url)

**Comment by arcturusannamalai** [comment]
![screen shot 2018-04-04 at 8 08 05 am](https://user-images.githubusercontent.com/3316245/38316330-5447f838-37df-11e8-86e6-fe78dadc8460.png)

Nice work! Thanks for fix.
