### ISSUE TITLE
Command line tamil tools not working

### ISSUE THREAD

**Issue by abuvanth** [Ezhil-Language-Foundation/open-tamil#152]
bash: tamilphonetic: command not found

**Comment by arcturusannamalai** [comment]
Please use like; 
tamilphonetic.py 

usually from /usr/local/bin/tamilphonetic.py


Also try, 'which tamilphonetic.py'

Please report what you can see.

**Comment by abuvanth** [comment]
![command line tools](https://user-images.githubusercontent.com/20999104/38292630-11d6c862-3802-11e8-950f-81ce638266e0.png)

tested in ubuntu 17.10 and kali linux 2017.3

**Comment by arcturusannamalai** [comment]
Abu, you are pulling in the version 0.67; my version this time is not setup correctly for default.

Please try, 'pip install open-tamil==0.7'  only.

Don't issue the 'pip install --upgrade open-tamil' command.

After installing 0.7 version you should see the tamilphonetic.py command line tools.

**Comment by abuvanth** [comment]
after pip install open-tamil==0.7
its working thanks.

**Comment by arcturusannamalai** [comment]
Thanks for checking!
