### ISSUE TITLE
Switching language from default Tamil to En throws 404

### ISSUE THREAD

**Issue by msathia** [Ezhil-Language-Foundation/open-tamil#158]
When I click En it takes to http://tamilpesu.us/i18n/setlang/  and it says Not Found. May be this is known issue, or already reported, if so pls close this.

**Comment by abuvanth** [comment]
already reported here 

https://github.com/Ezhil-Language-Foundation/tamilpesu_us/issues/1

**Comment by arcturusannamalai** [comment]
Marking as closed; this is a bug in tamillpesu.us hosting. Source repository web app when run as properly hosted Django site will not show this error.
