### ISSUE TITLE
English word in Tamil - classifier web interface

### ISSUE THREAD

**Issue by arcturusannamalai** [Ezhil-Language-Foundation/open-tamil#164]
Add web interface to ML classifier that can show if a given word is Tamil or English-transliterated Tamil word.

**Comment by abuvanth** [comment]
Web interface for ML classifier is done.

**Comment by abuvanth** [comment]
test_scaler.pkl and test_nn.pkl should be placed in opentamilapp folder

**Comment by arcturusannamalai** [comment]
Nice work! Thanks, Abu.

**Comment by arcturusannamalai** [comment]
Will you be sending a pull request ? or push to repo ?

**Comment by arcturusannamalai** [comment]
Abu's commit: https://github.com/Ezhil-Language-Foundation/open-tamil/commit/1d4faa3e65360ee2652b53eccc4b63f9ef7d3047
