### ISSUE TITLE
Tamil - Morse-code 

### ISSUE THREAD

**Issue by arcturusannamalai** [Ezhil-Language-Foundation/open-tamil#170]
Can we compose a Tamil Morse-code ?
1. Start with a frequency count of Tamil letters from various sources
2. Build a probability distribution from the frequency counts
3. Build a Huffman code using the above distribution
4. Each letter of Tamil alphabet gets a Morse code : 0 = '.', 1 - '-'.
    புள்ளி, கோடு.

**Comment by arcturusannamalai** [comment]
commit ac9e9dc093df1ef632c17bb70cc4f294e8b40db9

**Comment by arcturusannamalai** [comment]
See: https://wordpress.com/post/ezhillang.blog/3197

**Comment by ssurenr** [comment]
Isn't 30 symbols enough?

**Comment by arcturusannamalai** [comment]
I think you are saying ceil(log2(30)) = 5bits is sufficient, by virtue of Abugida / Uyir-Mei syllabic nature of Tamil. However when expressed in code, it may require some complex decoding logic.

This is a contentious matter! Ithanai sariyaaga seivatharkku comment-section-ai thaandi muyarchikka vendum; yenn ninga ithanai oru script-aaga meroklla koodathu @ssurenr  ? tamil.utf8.splitMeiUyir can help!

**Comment by ssurenr** [comment]
ஆம். 247 மோர்ஸ் சிம்பல்களை நினைவில் வைப்பதை விட 30 எளிதல்லவா. டீகோட் செய்யும்போது வரும் சிக்கலுக்கு ஒரு எடுத்துக்காட்டு தர இயலுமா?
ஒரு issue உருவாக்கி எனக்கு ஒப்படையுங்கள்.
