### ISSUE TITLE
Word Count issue in web interface

### ISSUE THREAD

**Issue by abuvanth** [Ezhil-Language-Foundation/open-tamil#171]
![word count](https://user-images.githubusercontent.com/20999104/44202322-42411680-a169-11e8-8e62-31ad0e46f36d.png)

Spaces are counted as a word.  In above pic. there are three words but  output says "மொத்த சொற்கள் 6 மற்றும் மொத்த எழுத்துகள் 11
" 
I think problem arises on javascript side.

**Comment by abuvanth** [comment]
https://github.com/Ezhil-Language-Foundation/open-tamil/commit/03b6199c779800d8ac2589945064486cb3e03d90  Fixed

**Comment by arcturusannamalai** [comment]
நல்ல முயற்சி / வழு நிக்கல் @abuvanth ! நன்றி
