### ISSUE TITLE
Html code appeared in reverse word functionality in webapp

### ISSUE THREAD

**Issue by abuvanth** [Ezhil-Language-Foundation/open-tamil#172]
![code](https://user-images.githubusercontent.com/20999104/44268590-90304a00-a24f-11e8-93c4-1a5b92fabcd1.png)

when delete text after input something, above html codes are appeared in output.

**Comment by abuvanth** [comment]
Fixed https://github.com/Ezhil-Language-Foundation/open-tamil/commit/da88828e90930782e7c4576bdb6faf10fd3e2320 https://github.com/Ezhil-Language-Foundation/open-tamil/commit/72fc451458d998b2ce3deaaa295074dbae2ec57d

**Comment by arcturusannamalai** [comment]
So nifty! Nice work.
