### ISSUE TITLE
opentamilweb - GET request can't send large amount of data

### ISSUE THREAD

**Issue by abuvanth** [Ezhil-Language-Foundation/open-tamil#174]
We should use POST method instead of GET method for sending large amount of data.

**Comment by arcturusannamalai** [comment]
Yes. Also we need to use batch jobs also ?

**Comment by abuvanth** [comment]
![error sandhi](https://user-images.githubusercontent.com/20999104/45011848-45c21200-b032-11e8-9ae8-8d4f854ebaae.png)


when submit large amount of input in sandhi checker GET method not handle this request, so we should use POST method. Becuase GET method allow only 1024 bytes.

1. GET requests have length restrictions

2. POST requests have no restrictions on data length

**Comment by abuvanth** [comment]
Fixed https://github.com/Ezhil-Language-Foundation/open-tamil/commit/fd4bac784a941d3b7933179d631db050b49cfb5a

**Comment by arcturusannamalai** [comment]
நன்றி அபு!
