### ISSUE TITLE
Enhancements to UTF-8 text processing in Tamil

### ISSUE THREAD

**Issue by msathia** [Ezhil-Language-Foundation/open-tamil#18]
Create a standard library that can 
1.Take any unicode input and try to return the codepoints
2. Provide a standard method for Level II rendering for each complex character( avoid canonical equivalence problem)
3. Provide a new index to all 247+ Character set. 
4. Return a  standard tamil character array 
5. Provide common string manipulation functions that are agnostic to encoding
    a. Char count
    b. Concatenate strings
    c. reverse the strings
    d. provide an array and return a string
    e. compare strings
    f. split string

**Comment by arcturusannamalai** [comment]
```
from tamil.utf8 import *
```
does most of these tasks. Maybe we should update the title as 'Enhancements to UTF-8 text processing in Tamil?'

**Comment by msathia** [comment]
Done.

**Comment by arcturusannamalai** [comment]
I think tamil.utf8.* modules provide all the said functionality. To be clear, I will list the items piecemeal:

1. Take any unicode input and try to return the codepoints: 
   - **tamil.utf8.get_letters**
2. Provide a standard method for Level II rendering for each complex character( avoid canonical equivalence problem)
    -  **track in separate ticket**
3. Provide a new index to all 247+ Character set.
    -  **Ignore for now; separate arrays are available for uyir, mei, agaram, etc.**
4. Return a standard tamil character array
    - **tamil.utf8.tamil_letters**
5. Provide common string manipulation functions that are agnostic to encoding
a. Char count: 
    - **len(tamil.utf8.get_letters())**
b. Concatenate strings: 
    - **Python can do this automatically**
c. reverse the strings: 
    - **tamil.utf8.reverse_word()**
d. provide an array and return a string: 
    - Standard Python is sufficient **u"".join(...)**
e. compare strings: 
    - **tamil.utf8.compare_words_lexicographic(word_a,word_b)** can be used with sorted() Python command to sort strings, or arrays.
f. split string: 
    - *Standard Python split is sufficient.*

**Comment by arcturusannamalai** [comment]
Sathia - please update details of missing item to ticket #137.
