### ISSUE TITLE
Fix pypi v0.95 release

### ISSUE THREAD

**Issue by arcturusannamalai** [Ezhil-Language-Foundation/open-tamil#192]
> (foo) /Users/muthu/devel/trial$python3 -m pip install open-tamil==0.95 --user
Collecting open-tamil==0.95
  Using cached https://files.pythonhosted.org/packages/12/8c/8b3b7565643fd5491b5ed623ec2faa3a1dd893b1a9fa2c3a7d58b0b78692/Open-Tamil-0.95.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dd/2zhwb5jn5zz5vkhdj1zyj1t40000gn/T/pip-install-fnqwmnsm/open-tamil/setup.py'"'"'; __file__='"'"'/private/var/folders/dd/2zhwb5jn5zz5vkhdj1zyj1t40000gn/T/pip-install-fnqwmnsm/open-tamil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/dd/2zhwb5jn5zz5vkhdj1zyj1t40000gn/T/pip-install-fnqwmnsm/open-tamil/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dd/2zhwb5jn5zz5vkhdj1zyj1t40000gn/T/pip-install-fnqwmnsm/open-tamil/setup.py", line 10, in <module>
        long_description = open('README.rst','r','UTF-8').read()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(foo) /Users/muthu/devel/trial$less foo/

**Comment by arcturusannamalai** [comment]
Fix: de91482fd20b42f41f365deaa163da254f77efaa

**Comment by prabhakar6372** [comment]
Hi Muthiah and Team


I would like to thank you and appreciate you for your efforts.. I am sure this module is going to be used by lot and in taking the beauty of tamil in different researches.. Even I got few ideas on researching tamil in different dimension post utilizing this module.. 


Once again a big kudos to you and your team.. 


Regards
Prabhakar

On November 26, 2019 at 11:09 PM, Muthiah Annamalai <notifications@github.com> wrote:



Closed #192.
