### ISSUE TITLE
Issue in converting bamini2unicode 

### ISSUE THREAD

**Issue by Parathantl** [Ezhil-Language-Foundation/open-tamil#193]
The encoding letters of bamini relevant to Unicode to some Tamil letters are not properly written.  
![Capture](https://user-images.githubusercontent.com/5859130/72178044-e1862f80-3396-11ea-934c-6d60ce49d551.PNG)

**Comment by Parathantl** [comment]
I made a pull request mentioning the issue title and the number.

**Comment by arcturusannamalai** [comment]
நன்றி பரதன்.
