### ISSUE TITLE
Image not found in pypi

### ISSUE THREAD

**Issue by SmartManoj** [Ezhil-Language-Foundation/open-tamil#230]
https://warehouse-camo.ingress.cmh1.psfhosted.org/06644c19a82070adbceb75217adc1bdd9f57d5dc/6f70656e2d74616d696c2d6c6f676f2e6a7067

**Comment by arcturusannamalai** [comment]
@SmartManoj  - can you explain the bug? I cannot understand the issue.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/99139090-d7d6f380-265b-11eb-9ea4-49ee56698875.png)

**Comment by SmartManoj** [comment]
https://pypi.org/project/Open-Tamil/

**Comment by arcturusannamalai** [comment]
Thanks for reporting!

**Comment by SmartManoj** [comment]
> [Link](https://pypi.org/project/Open-Tamil/#version-0-96:~:text=%E0%AE%A4%E0%AE%BF%E0%AE%B1%20%E0%AE%AE%E0%AF%82%E0%AE%B2%20%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D%20%E0%AE%95%E0%AE%B0%E0%AF%81%E0%AE%B5%E0%AE%BF%E0%AE%95%E0%AE%B3%E0%AF%8DVersion%200.96)
> 
> ![image](https://user-images.githubusercontent.com/7231077/99139090-d7d6f380-265b-11eb-9ea4-49ee56698875.png)

Still the samw
