### ISSUE TITLE
How to build this library from the scratch?

### ISSUE THREAD

**Issue by kajan26** [Ezhil-Language-Foundation/open-tamil#232]
இந்த மென்பொருள் தொகுப்பிற்கு பங்களிக்க விரும்புகிறேன். எவ்வாறு இத்தொகுப்பை ஆரம்பத்திலிருந்து கட்டமைத்து இயக்குவது (Build from the scratch and run) ? எதாவது குறிப்புகள் இருப்பின் பகிர்க..

**Comment by arcturusannamalai** [comment]
```
$ python3 setup.py sdist build
$ python3 setup.py sdist install --user
```

என்ற கட்டளைகளின் படி நீங்கள் இதனை நிறுவலாம்.

மேலும் `$./unittest3.sh` என்ற கட்டளையினால் நீங்கள் செய்யும் மாற்றங்களை பரிசோதனை செய்யலாம்.
