### ISSUE TITLE
Add support for ISO standard unicode tamil to roman transliteration

### ISSUE THREAD

**Issue by tshrinivasan** [Ezhil-Language-Foundation/open-tamil#233]
Looking for a support on unicode tamil to roman letters transliteration.

Example -    
இன்றைய இலக்கியம்  = inRaiya ilakkiyam

Found the code here works well for this
https://github.com/atvKumar/UniAnu/blob/master/unicode_to_roman.py

Check the repo, add this and other required utilities.

**Comment by arcturusannamalai** [comment]
@tshrinivasan have you seen this work? Does it meet your requirements? https://github.com/Ezhil-Language-Foundation/open-tamil/blob/master/tests/transliterate_tests.py

**Comment by Natkeeran** [comment]
There are different transliteration standards.  One method (not sure if there is a particular standard) is commonly used for typing.  The second one is based on ISO standard, mostly used for academic purposes (i.e catalogues, text books).  The one in the tests seemed to implement the first method (need to confirm).  Seems like the the ISO standard has not been implemented.  

Example:
```
tamil_str = "சாமி. சிதம்பரனார் நூற் களஞ்சியம்"
azhagi_table = azhagi.Transliteration.table
eng_str = algorithm.Tamil2English.transliterate(azhagi_table, tamil_str)
```
Results in 
```
'chAmi. chidhambaranAr ndhUR KaLaGnchiyam'
```

If ISO standard is applied (https://www.ushuaia.pl/transliterate/?ln=en), it should result in 
```
cāmi. citamparaṉār nūṟ kaḷañciyam
```

More Info:
https://en.wikipedia.org/wiki/ISO_15919
https://www.ushuaia.pl/transliterate/?ln=en
https://github.com/herstand/tamil-transliteration/blob/master/TransliterateTamil.js

**Comment by tshrinivasan** [comment]
https://aksharamukha.appspot.com/converter

This has tamil to roman iso transliteration convertor.

Has a python package too

https://aksharamukha.appspot.com/python


https://aksharamukha.appspot.com/documentation

 Check the documentation here

**Comment by arcturusannamalai** [comment]
If you try in Open-Tamil, the following snippet, you can see similar to ISO results,

```
tamil_str = "சாமி. சிதம்பரனார் நூற் களஞ்சியம்"
UOM_table = UOM.Transliteration.table
eng_str = algorithm.Tamil2English.transliterate(UOM_table, tamil_str)

```

the output
`'cāmi. citimprṉāir nūiṟ kḷiñciyim'
`

**Comment by arcturusannamalai** [comment]
I'm exploring the issue now; it seems more work needs to be done on algorithm/transliteration table side at this moment; once we add support I'll update package release.

However at this time, maybe you can go with other package as @tshrinivasan has suggested.

**Comment by arcturusannamalai** [comment]
> I'm exploring the issue now; it seems more work needs to be done on algorithm/transliteration table side at this moment; once we add support I'll update package release.
> 
> However at this time, maybe you can go with other package as @tshrinivasan has suggested.

@tshrinivasan @Natkeeran  - developer branch has this support now. Please try:

```
        from transliterate import azhagi, jaffna, combinational, UOM, ISO, itrans, algorithm
        ISO_table = ISO.ReverseTransliteration.table
        expected = 'cāmi. citamparaṉār nūṟ kaḷañciyam'
        tamil_str = "சாமி. சிதம்பரனார் நூற் களஞ்சியம்"
        eng_str = algorithm.Direct.transliterate(ISO_table,tamil_str)
        self.assertEqual(expected,eng_str)
```

**Comment by Natkeeran** [comment]
@arcturusannamalai have you already merged this.  How do I pull in the latest via pip?

I do notice some differences between the example you posted and https://www.ushuaia.pl/transliterate/?ln=en.

**Comment by Natkeeran** [comment]
@tshrinivasan 

Error during installation.

```
nat@LIB-6HSWM53:~/tools/open-tamil$ sudo python3 setup.py install
[sudo] password for nat: 
running install
running bdist_egg
running egg_info
writing Open_Tamil.egg-info/PKG-INFO
writing dependency_links to Open_Tamil.egg-info/dependency_links.txt
writing top-level names to Open_Tamil.egg-info/top_level.txt
error: package directory 'tamil-sandhi-checker/tamilsandhi' does not exist
nat@LIB-6HSWM53:~/tools/open-tamil$ 
nat@LIB-6HSWM53:~/tools/open-tamil$ git log -1
commit e6ee9c80f16ee1718c08a62a134fc1e9ee51c868 (HEAD -> main, origin/main, origin/HEAD)
Author: Muthu Annamalai <ezhillang@gmail.com>
Date:   Sat Jan 30 19:53:15 2021 -0800

    update sumodule org

```

**Comment by arcturusannamalai** [comment]
@Natkeeran  - please refer to updating the submodule instructions within the README.
