### ISSUE TITLE
spelling mistake in MANIFEST

### ISSUE THREAD

**Issue by Natkeeran** [Ezhil-Language-Foundation/open-tamil#236]
https://github.com/Ezhil-Language-Foundation/open-tamil/blob/main/MANIFEST.in#L3

(thank you to irfan for pointing this issue out)

Also, does it expect this folder /open-tamil/tamil-sandhi-checker/tamilsandhi

Related to https://github.com/Ezhil-Language-Foundation/open-tamil/issues/233

**Comment by arcturusannamalai** [comment]
Resolved
