### ISSUE TITLE
Transliteration issue with ஜ character not being transliterated

### ISSUE THREAD

**Issue by CRE2525** [Ezhil-Language-Foundation/open-tamil#239]
Hello, I opened an issue a few weeks ago about the ந் character not being transliterated ([here](https://github.com/Ezhil-Language-Foundation/open-tamil/issues/237)), which was quickly fixed (Thank you!). However, it looks like I found another character which also does not get transliterated, which is the ஜ character. Here is an example:

![Screenshot from 2021-02-22 15-02-43](https://user-images.githubusercontent.com/55265361/108776545-c8e7c300-751f-11eb-851a-730c6d099f04.png)

As seen in the print statements at the bottom, it doesn't seem to change. Hopefully this is an easy fix as well. Thanks again!

**Comment by arcturusannamalai** [comment]
@CRE2525 - thanks for bug report; what is the correct transliteration according to ISO? Is it just "j" or "ja" ?

**Comment by CRE2525** [comment]
According to [this](https://www.ushuaia.pl/transliterate/?ln=en) website, it's 'ja'; however, I do not speak Tamil so I can't verify that.

**Comment by arcturusannamalai** [comment]
@CRE2525  - it is JA
