### ISSUE TITLE
Overwriting Transliterate Package

### ISSUE THREAD

**Issue by ross-oc-dg** [Ezhil-Language-Foundation/open-tamil#254]
There's already a package on PyPI named Transliterate:

https://pypi.org/project/transliterate/

At present, if I do pip install open-tamil, it overwrites this package. I believe the fix is a small change in how open-tamil is packaged, but I'm not an expert on packaging.

**Comment by arcturusannamalai** [comment]
that package is formed only in 2013 https://github.com/barseghyanartur/transliterate/commit/6c8c89b5d645999fe84a68d6e806a464966b7962 whereas we are older; since there is nobody who uses both these packages this is a no-action ticket at this time.
