### ISSUE TITLE
tamil.utf8.all_tamil() for longer text

### ISSUE THREAD

**Issue by rudhbaskaran** [Ezhil-Language-Foundation/open-tamil#255]
The current implementation expects a "word" as input and returns True if all the characters in it fall within the Tamil Unicode code block and False otherwise. It should be noted that this is similar to the behavior of string functions `isalpha()` and `isalnum()` in python.

I felt another function to test whether a whole passage/ text is Tamil (without any English alphabets) would be useful. Currently, the user will have to loop thro' each word and then check all_tamil separately. Instead, I wonder if there should be a better implementation directly available as part of `utf8`.

**Comment by arcturusannamalai** [comment]
`all(list(map(utf8.all_tamil,re.split("\s+",str))))`

should do the trick

can you check this function and submit a patch ? Please add a unittest

**Comment by rudhbaskaran** [comment]
Have added this function and have also created a test case for the
function. Facing some git issue on my Mac; will submit PR once I fix it.

Thanks, Baskaran

**Comment by rudhbaskaran** [comment]
I think it is natural for the Tamil text to have punctuation and numbers. So, here is a slightly modified version:

`all(list(map(check_ta, set(get_letters(str)))))`

This also avoids looping over the words and instead takes unique characters for testing. The helper function `check_ta()` does this:

`return all_tamil(ch) or ch in string.punctuation or ch.isdigit() or ch.isspace()`

**Comment by arcturusannamalai** [comment]
Resolved by https://github.com/Ezhil-Language-Foundation/open-tamil/pull/256

**Comment by arcturusannamalai** [comment]
Resolved by https://github.com/Ezhil-Language-Foundation/open-tamil/pull/256
