### ISSUE TITLE
Document summary - wc - for Tamil text.

### ISSUE THREAD

**Issue by arcturusannamalai** [Ezhil-Language-Foundation/open-tamil#68]
A tool like 'wc' on Linux, but for working with UTF-8 encoded Tamil characters in file.
Reported new-lines, are same as wc -l, but the '-c', '-w' options count legal Tamil letters, and words not unicode-points.

**Comment by ssurenr** [comment]
Hi @arcturusannamalai, Could you make me a contributor? I would like to start my contribution starting with this issue.

**Comment by arcturusannamalai** [comment]
OK @ssurenr. Please fork the repository and send me a pull request. Once you have made first contribution I can add you as direct contributor. This is general process I have used and it works well.
