### ISSUE TITLE
TACE 16 to UTF8 and back converter

### ISSUE THREAD

**Issue by msathia** [Ezhil-Language-Foundation/open-tamil#84]
Convert UTF8 input and respond back with a TACE16 Encoded String. 
Revert the conversion in another method. 
Unit test cases

**Comment by arcturusannamalai** [comment]
This work is already present in Open-Tamil due to encoding work by @arulalant 
We can convert back/forth using tamil.txt2unicode and tamil.unicode2txt module functions as also demonstrated in http://tamilpesu.us/tsci/ website.
